services:
  backend:
    image: backend:latest
    ports:
      - "8000:8000"
    env_file:
      - /home/ec2-user/.env
    restart: unless-stopped
    volumes:
      - /home/ec2-user/logs:/app/logs
    networks:
      - app-net

  frontend:
    image: frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
