services:
  backend:
    image: backend:latest
    ports:
      - "8000:8000"
    env_file:
      - /home/ec2-user/.env
    restart: unless-stopped

  frontend:
    image: frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
